version: '3'
services:

  dash:
    image: 'bankbuddy.azurecr.io/dash-analytics:v1.0.1'
    container_name: 'dash'
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
      - "8052:8052"
    volumes:
      - .:/analytics
    networks:
     - dbnet

  postgres_console:
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=console
      - POSTGRES_PASSWORD=buddy
      - POSTGRES_USER=buddy
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - dbnet

networks:
    dbnet:
      driver: bridge
