version: '3'
services:

  dash:
    image: 'bankbuddy.azurecr.io/dash-analytics:v1.0.1'
    container_name: 'dash'
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
      - "8052:8052"
    volumes:
    - .:/analytics